x-environment-vars: &environment-vars
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

services:
  validator-db:
    image: postgres:11
    environment:
      <<: *environment-vars
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - validator-db:/var/lib/postgresql/data
  
  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile.dbmate
    entrypoint: bash bin/migrate.sh
    environment:
      <<: *environment-vars
    volumes:
      - .:/app
    depends_on:
      validator-db:
        condition: service_healthy
    restart: "no"

  redis:
    restart: always
    image: redis:7.4.0
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  validator-db:
  redis_data: